### PR TITLE
Fix product nomenclature

### PR DESCRIPTION
**Pull request by soldnermike**
#feedback

### CODE REVIEW

**Comment by gibron** [comment]
@soldnermike  Looks good; what about admin links?

**Comment by soldnermike** [comment]
TBH I think we should remove those entirely unless we know for certain the URL. Is everyone on admin v3? Is this reliable? https://{NETWORK_NAME}.admin.fyre.co/v3/content for everybody? And the support link should be removed.

**Comment by gibron** [comment]
Understood and agreed; https://{NETWORK_NAME}.admin.fyre.co/v3/content should be reliable for all Enterprise but not Community. Lets close the scope on this to only apps and we can discuss Admin and Support separately.

**Comment by gibron** [comment]
Merging.

**Pull request merged**
